### ISSUE TITLE
Birinchi section

### ISSUE THREAD

**Issue by raxmono** [raxmono/Team-working-6-lesson#1]
Birinchi prect ... faqat main qismi qilinsin @rahmonjonqosimov

**Comment by raxmono** [comment]
Ikkinchi prect ... faqat main qismi qilinsin @sarvardev10

**Comment by raxmono** [comment]
Turtinchi prect ... @bexzod1509

**Comment by raxmono** [comment]
Beshinchi prect ... main qismi qilinsin @Yusuf3114

**Comment by rahmonjonqosimov** [comment]
> Birinchi prect ... faqat main qismi qilinsin @rahmonjonqosimov
